### ISSUE TITLE
AttributeError: 'TData' object has no attribute 'eis'

### ISSUE THREAD

**Issue by luisfredgs** [iHeartGraph/Euler#1]
I tried to reproduce the experiments on LANL dataset. However, the following error has occurred:
```
Early stopping!
Exiting train loop
Avg TPE: 46.8585s
worker0: Reloading 143341 - 150885
Finding start: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3340/3340 [00:00<00:00, 10767.98it/s]
Seconds read: 3601it [00:00, 11611.27it/s]                                                                                                                                                    
Finding start: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6940/6940 [00:00<00:00, 12623.22it/s]
Seconds read: 5401it [00:00, 9830.02it/s]                                                                                                                                                     
Joining Data objects

On WorkerInfo(id=0, name=worker0):
AttributeError("'TData' object has no attribute 'eis'")
Traceback (most recent call last):
  File "/home/lfgs/venvs/CT/lib/python3.8/site-packages/torch/distributed/rpc/internal.py", line 204, in _run_function
    result = python_udf.func(*python_udf.args, **python_udf.kwargs)
  File "/home/lfgs/Documents/CT/Euler_lanl_experiments/models/utils.py", line 6, in _call_method
    return method(rref.local_value(), *args, **kwargs)
  File "/home/lfgs/Documents/CT/Euler_lanl_experiments/models/euler_interface.py", line 91, in load_new_data
    self.module.data = loader(jobs, **kwargs)
  File "/home/lfgs/Documents/CT/Euler_lanl_experiments/loaders/load_lanl.py", line 84, in load_lanl_dist
    eis = data_reduce('eis')
  File "/home/lfgs/Documents/CT/Euler_lanl_experiments/loaders/load_lanl.py", line 79, in <lambda>
    data_reduce = lambda x : sum([datas[i].__getattribute__(x) for i in range(workers)], [])
  File "/home/lfgs/Documents/CT/Euler_lanl_experiments/loaders/load_lanl.py", line 79, in <listcomp>
    data_reduce = lambda x : sum([datas[i].__getattribute__(x) for i in range(workers)], [])
AttributeError: 'TData' object has no attribute 'eis'
```
My environment:
- Python 3.8
- Pytorch 1.10.0+cu113

**Comment by hadizand** [comment]
> I tried to reproduce the experiments on LANL dataset. However, the following error has occurred:
> 
> ```
> Early stopping!
> Exiting train loop
> Avg TPE: 46.8585s
> worker0: Reloading 143341 - 150885
> Finding start: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3340/3340 [00:00<00:00, 10767.98it/s]
> Seconds read: 3601it [00:00, 11611.27it/s]                                                                                                                                                    
> Finding start: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6940/6940 [00:00<00:00, 12623.22it/s]
> Seconds read: 5401it [00:00, 9830.02it/s]                                                                                                                                                     
> Joining Data objects
> 
> On WorkerInfo(id=0, name=worker0):
> AttributeError("'TData' object has no attribute 'eis'")
> Traceback (most recent call last):
>   File "/home/lfgs/venvs/CT/lib/python3.8/site-packages/torch/distributed/rpc/internal.py", line 204, in _run_function
>     result = python_udf.func(*python_udf.args, **python_udf.kwargs)
>   File "/home/lfgs/Documents/CT/Euler_lanl_experiments/models/utils.py", line 6, in _call_method
>     return method(rref.local_value(), *args, **kwargs)
>   File "/home/lfgs/Documents/CT/Euler_lanl_experiments/models/euler_interface.py", line 91, in load_new_data
>     self.module.data = loader(jobs, **kwargs)
>   File "/home/lfgs/Documents/CT/Euler_lanl_experiments/loaders/load_lanl.py", line 84, in load_lanl_dist
>     eis = data_reduce('eis')
>   File "/home/lfgs/Documents/CT/Euler_lanl_experiments/loaders/load_lanl.py", line 79, in <lambda>
>     data_reduce = lambda x : sum([datas[i].__getattribute__(x) for i in range(workers)], [])
>   File "/home/lfgs/Documents/CT/Euler_lanl_experiments/loaders/load_lanl.py", line 79, in <listcomp>
>     data_reduce = lambda x : sum([datas[i].__getattribute__(x) for i in range(workers)], [])
> AttributeError: 'TData' object has no attribute 'eis'
> ```
> 
> My environment:
> 
> * Python 3.8
> * Pytorch 1.10.0+cu113

Hi,

I faced the same error, 
could you resolve this issue?

python : 3.8.8
torch: 1.11.0
joblib : 1.1.0
thanks

**Comment by zazyzaya** [comment]
Hi @hadizand, the issue has been resolved in the most recent commit. Please let me know if there is anything else I can help with. 
Thanks!
--Isaiah
