### ISSUE TITLE
Could the author please provide the requirements.txt？

### ISSUE THREAD

**Issue by Meoooww** [iHeartGraph/Euler#8]
Environmental issues keep me reporting errors when reproducing. It would be very helpful if anyone could provide requirements.txt

**Comment by zcxsythenew** [comment]
I need it, too.

**Comment by zcxsythenew** [comment]
@zazyzaya @iHeartGraph

**Comment by zazyzaya** [comment]
Added. Also please note: I used Python 3.10.8 (though I think it's compatible with Python >= 3.6)

**Comment by Meoooww** [comment]
thanks

**Comment by zcxsythenew** [comment]
> Added. Also please note: I used Python 3.10.8 (though I think it's compatible with Python >= 3.6)

Hi @zazyzaya , is this requirements.txt complete? If I run `lanl_experiments/runall_LANL.sh`, it will complain `ModuleNotFoundError: No module named 'torch_sparse'`.

**Comment by zazyzaya** [comment]
Hey, @zcxsythenew . Looks like `piputils` missed some modules. I regenerated a requirements.txt file with `conda list --export` that should have everything
