### ISSUE TITLE
Why prior_ work.py did not output for a long time

### ISSUE THREAD

**Issue by Meoooww** [iHeartGraph/Euler#9]
![image](https://github.com/iHeartGraph/Euler/assets/56733007/b5b63552-f95f-442f-97db-6fa06cee3e6a)
Even the first epoch did not output
this is how I ran it:

1. obtained the preprocessed dataset(by loaders/split.py):
   ![image](https://github.com/iHeartGraph/Euler/assets/56733007/caf920f7-41ac-4573-a1f0-afc579dac443)
2. specify the file locations in loaders/load_lanl.py
  ![image](https://github.com/iHeartGraph/Euler/assets/56733007/834f2105-5f40-40ab-9d1e-6c1b9f3436ce)

**Comment by zazyzaya** [comment]
Possibly a hardware issue. This is meant to be distributed across multiple CPUs. Trying to run it on a normal PC will result in hanging. What are your machine's specs, @Meoooww ?

**Comment by Meoooww** [comment]
> Possibly a hardware issue. This is meant to be distributed across multiple CPUs. Trying to run it on a normal PC will result in hanging. What are your machine's specs

yes, you are right. I am a newcomer in this field, and I do run it on a normal PC. Is it impossible to work? Or do I have to use complex distributed systems as mentioned in the paper？

**Comment by zazyzaya** [comment]
It will work it will just take a really long time. Try using a smaller subset of the training data if you aren't distributing it
